[package]
name = "focus_staking"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
pet_token = { local = "../pet_token" }

[addresses]
focus_staking = "0x0"
pet_token = "0xf20998a7f30a94ead030ad6528899aafff4693900fb4b547f59882615a0c24a4"
